/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timeMachine.Forms;

import java.text.SimpleDateFormat;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import timeMachine.Classes.TimeClass;

/**
 *
 * @author shahar
 */



public class TimeTracker extends javax.swing.JFrame {

    /**
     * Creates new form TimeTracker
     */
    public TimeTracker() {
        initComponents();
        theTime = new TimeClass();
        TimeTrackerListener listen = new TimeTrackerListener();
        listen.t=this;//this is so wrong
        this.startText.getDocument().addDocumentListener(listen);
        this.stopText.getDocument().addDocumentListener(listen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startText = new javax.swing.JTextField();
        stopText = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalHours = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Start");

        jLabel2.setText("Stop");

        startText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                startTextInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        startText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTextActionPerformed(evt);
            }
        });
        startText.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                startTextPropertyChange(evt);
            }
        });

        stopText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopTextActionPerformed(evt);
            }
        });

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Stop");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("New");

        jLabel3.setText("Total: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(startText)
                            .addComponent(stopText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalHours)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(startText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalHours))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private TimeClass theTime;
    private void startTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTextActionPerformed
        manualUpdate();
    }//GEN-LAST:event_startTextActionPerformed

    private void stopTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopTextActionPerformed
        // TODO add your handling code here:
        manualUpdate();
    }//GEN-LAST:event_stopTextActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        if(theTime.isStarted())
        {
            showMessageDialog(null,"Already started");
        }
        else
        {
            theTime.startNow();
            updateView();
        }
    }//GEN-LAST:event_startButtonActionPerformed

    public void manualUpdate()
    {
        if (!this.startText.getText().equals(""))
        {
            try
            {
                theTime.start = f.parse(this.startText.getText());
            }
            catch (Exception exc)
            {
                //showMessageDialog(null,"Bad start date format");
            }
        }
        if (!this.stopText.getText().equals(""))
        {
            try
            {
                theTime.end = f.parse(this.stopText.getText());
            }
            catch (Exception exc)
            {
                //showMessageDialog(null,"Bad start date format");
            }
        }
        updateTotalTime();
    }
    SimpleDateFormat f = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    public void updateView()
    {
        
        if (theTime.isStarted())
        {
            this.startText.setText(f.format(theTime.start));
        }
        if (theTime.isEnded())
        {
            this.stopText.setText(f.format(theTime.end));
        }
        updateTotalTime();
    }
    public void updateTotalTime()
    {
        if (theTime.isDone())
        {
            this.totalHours.setText(String.valueOf(theTime.getTotalTime()));
            System.out.println("here with " + String.valueOf(theTime.getTotalTime()));
        }
    }
    public void writeToDB()
    {
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(theTime.isEnded())
        {
            showMessageDialog(null,"Already ended");
        }
        else
        {
            theTime.endNow();
            updateView();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void startTextPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_startTextPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_startTextPropertyChange

    private void startTextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_startTextInputMethodTextChanged
        // TODO add your handling code here:
        manualUpdate();
    }//GEN-LAST:event_startTextInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeTracker().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField startText;
    private javax.swing.JTextField stopText;
    private javax.swing.JLabel totalHours;
    // End of variables declaration//GEN-END:variables
}
